id = "swift"
name = "Swift"
description = "Swift support."
version = "0.4.6"
schema_version = 1
authors = [
    "ejjonny <https://github.com/ejjonny>",
    "Samuser107 L.Longheval <samuser107@gmail.com>",
]
repository = "https://github.com/zed-extensions/swift"

[language_servers.sourcekit-lsp]
name = "sourcekit-lsp"
languages = ["Swift", "C", "C++", "Objective-C", "Objective-C++"]

[language_servers.sourcekit-lsp.language_ids]
Swift = "swift"
C = "c"
"C++" = "cpp"
"Objective-C" = "objective-c"
"Objective-C++" = "objective-cpp"

[grammars.swift]
repository = "https://github.com/alex-pinkus/tree-sitter-swift"
commit = "33e56e4e2a6455f3fd4e04cfe5c7a314d498612d"

[grammars.objc]
repository = "https://github.com/amaanq/tree-sitter-objc"
commit = "181a81b8f23a2d593e7ab4259981f50122909fda"

[debug_adapters.Swift]
schema_path = "debug_adapter_schemas/Swift.json"
